goxf:
    enableConsole: true
    enableMetric: false
    enablePprof: false
    enableRegister: false
    enableTrace: false
    serviceName: examples
i18n:
    default:
        language: zh
        path: i18n
jwt:
    expiresAt: 12h
    signingKey: your_secret_key_heresssssadaswqeq
logger:
    default:
        addCaller: true
        async: false
        callerSkip: 2
        dir: .
        enableTimeLayout: true
        level: debug
        maxAge: 1
        maxBackup: 2
        maxSize: 1
server:
    gin:
        default:
            addr: :8888
